name: CI

on:
  push:
    branches: ["ci-impl"] # GH Action test. Delete on PR resolve

  pull_request:
    branches: ["main"]

jobs:
  test-with-coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

        psql-host: [localhost]
        psql-port: [5432]
        psql-user: [developer]
        psql-password: [testing]
        psql-database: [forum_api]

    steps:
      - name: setup psql on ${{ matrix.psql-host }}
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: latest
          postgresql user: ${{ matrix.psql-user }}
          postgresql password: ${{ matrix.psql-password }}
          postgresql db: ${{ matrix.psql-database }}

      - name: setup node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: install dependencies
        run: npm install

      - name: setup db environments
        run: npm run pgm up
        env:
          # PostgreSQL config
          PGHOST: ${{ matrix.psql-host }}
          PGPORT: ${{ matrix.psql-port }}
          PGUSER: ${{ matrix.psql-user }}
          PGPASSWORD: ${{ matrix.psql-password }}
          PGDATABASE: ${{ matrix.psql-database }}

      - name: run test
        run: npm test
        env:
          CI: true
          # PostgreSQL config
          PGHOST_TEST: ${{ matrix.psql-host }}
          PGPORT_TEST: ${{ matrix.psql-port }}
          PGUSER_TEST: ${{ matrix.psql-user }}
          PGPASSWORD_TEST: ${{ matrix.psql-password }}
          PGDATABASE_TEST: ${{ matrix.psql-database }}

          # JWT config
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
          ACCCESS_TOKEN_AGE: ${{ secrets.ACCCESS_TOKEN_AGE }}
